'use client'

import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import type { VerdictData } from '@/lib/types'
import MonoLabel from '@/components/ui/MonoLabel'

interface ExportDossierProps {
  verdict: VerdictData
  companyName: string
}

function formatMarkdownExport(verdict: VerdictData, companyName: string): string {
  const date = new Date().toUTCString()
  const verdictLabel = verdict.verdict.toUpperCase()
  const riskEmoji = verdict.risk_score >= 67 ? '🔴' : verdict.risk_score >= 34 ? '🟡' : '🟢'

  const vulnList = verdict.vulnerabilities.map(v =>
    `- **[${v.severity}]** ${v.description}${v.details ? `\n  > ${v.details}` : ''}`
  ).join('\n')

  const citationList = (verdict.citations ?? []).map(c =>
    `- **[${c.id}]** *${c.source_document}*\n  > "${c.snippet}"\n  Relevance: ${c.relevance}`
  ).join('\n')

  const chainList = verdict.reasoning_chain.map((s, i) =>
    `${i + 1}. **${s.agent.toUpperCase()}** (${s.api}) — Confidence: ${s.confidence}%`
  ).join('\n')

  return `# AEGIS INTELLIGENCE DOSSIER
## ${companyName}
**Generated:** ${date}
**Verdict:** ${riskEmoji} ${verdictLabel} | **Risk Score:** ${verdict.risk_score}/100

---

## Executive Summary

${verdict.summary}

---

## Vulnerabilities

${vulnList || '_None identified._'}

---

## Reasoning Chain

${chainList}

---

## Citations

${citationList || '_No citations attached._'}

---

*This dossier was generated by Aegis Agent. It is for informational purposes only and does not constitute financial or legal advice.*
`
}

export default function ExportDossier({ verdict, companyName }: ExportDossierProps) {
  const [status, setStatus] = useState<'idle' | 'success'>('idle')

  const handleExportMarkdown = () => {
    const md = formatMarkdownExport(verdict, companyName)
    const blob = new Blob([md], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `aegis-dossier-${companyName.replace(/\s+/g, '-').toLowerCase()}.md`
    a.click()
    URL.revokeObjectURL(url)
    setStatus('success')
    setTimeout(() => setStatus('idle'), 3000)
  }

  const handleExportJSON = () => {
    const json = JSON.stringify({ company: companyName, generated_at: new Date().toISOString(), verdict }, null, 2)
    const blob = new Blob([json], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `aegis-dossier-${companyName.replace(/\s+/g, '-').toLowerCase()}.json`
    a.click()
    URL.revokeObjectURL(url)
    setStatus('success')
    setTimeout(() => setStatus('idle'), 3000)
  }

  return (
    <div className="flex items-center gap-3">
      <MonoLabel className="text-on-surface-variant/60">EXPORT DOSSIER</MonoLabel>

      <button
        id="export-dossier-md"
        onClick={handleExportMarkdown}
        className="flex items-center gap-2 px-3 py-2 rounded-lg bg-surface-container border border-border-subtle text-xs font-mono text-on-surface-variant hover:text-primary hover:border-primary transition-all duration-200"
      >
        <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z"/>
          <polyline points="14 2 14 8 20 8"/>
        </svg>
        .MD
      </button>

      <button
        id="export-dossier-json"
        onClick={handleExportJSON}
        className="flex items-center gap-2 px-3 py-2 rounded-lg bg-surface-container border border-border-subtle text-xs font-mono text-on-surface-variant hover:text-cyan-agent hover:border-cyan-agent transition-all duration-200"
      >
        <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <polyline points="16 18 22 12 16 6"/><polyline points="8 6 2 12 8 18"/>
        </svg>
        .JSON
      </button>

      <AnimatePresence>
        {status === 'success' && (
          <motion.span
            initial={{ opacity: 0, x: -6 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0 }}
            className="text-[10px] font-mono text-emerald-agent flex items-center gap-1"
          >
            <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5"><polyline points="20 6 9 17 4 12"/></svg>
            Downloaded
          </motion.span>
        )}
      </AnimatePresence>
    </div>
  )
}
