/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "stack-md": "16px",
        "stack-lg": "32px",
        "stack-sm": "8px",
        gutter: "24px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        base: "4px",
      },
      fontFamily: {
        body: ["var(--font-body)"],
        "label-caps": ["var(--font-mono)"],
        headline: ["var(--font-display)"],
        display: ["var(--font-display)"],
        mono: ["var(--font-mono)"],
        code: ["var(--font-mono)"],
      },
      fontSize: {
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "500" }],
        "code-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "display-xl": ["72px", { lineHeight: "80px", letterSpacing: "-0.04em", fontWeight: "700" }],
        "display-xl-mobile": ["40px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
      colors: {
        surface: "var(--surface)",
        "surface-dim": "var(--surface-dim)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "surface-container-low": "var(--surface-container-low)",
        "surface-container": "var(--surface-container)",
        "surface-container-high": "var(--surface-container-high)",
        "surface-container-highest": "var(--surface-container-highest)",
        "surface-bright": "var(--surface-bright)",
        "surface-glass": "var(--surface-glass)",
        "surface-variant": "var(--surface-variant)",
        "on-surface": "var(--on-surface)",
        "on-surface-variant": "var(--on-surface-variant)",
        "text-muted": "var(--text-muted)",
        "on-background": "var(--on-background)",
        "border-subtle": "var(--border-subtle)",
        "outline-variant": "var(--outline-variant)",
        outline: "var(--outline)",
        "accent-luminous": "var(--accent-luminous)",
        primary: "var(--primary)",
        "primary-container": "var(--primary-container)",
        "on-primary": "var(--on-primary)",
        "on-primary-container": "var(--on-primary-container)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
        secondary: "var(--secondary)",
        "secondary-container": "var(--secondary-container)",
        "on-secondary-container": "var(--on-secondary-container)",
        "cyan-agent": "var(--cyan-agent)",
        "rose-agent": "var(--rose-agent)",
        "emerald-agent": "var(--emerald-agent)",
        "amber-agent": "var(--amber-agent)",
        "indigo-init": "var(--indigo-init)",
        "crimson-reject": "var(--crimson-reject)",
        error: "var(--crimson-reject)",
        "error-container": "#93000a",
      },
      transitionTimingFunction: {
        physics: "var(--ease-physics)",
        "quintic-out": "var(--ease-quintic-out)",
      },
      transitionDuration: {
        enter: "var(--duration-enter)",
        quick: "var(--duration-quick)",
      },
      boxShadow: {
        glow: "var(--glow-primary)",
        "glow-primary": "var(--glow-primary)",
        "glow-hover": "var(--glow-primary-hover)",
        "glow-primary-hover": "var(--glow-primary-hover)",
        "glow-cyan": "var(--glow-cyan)",
      },
    },
  },
  plugins: [],
};
